modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/${github_name}/issues"


[[mods]]
modId = "argonauts"
version = "${version}"
displayName = "Argonauts"
updateJSONURL="https://api.modrinth.com/updates/${modrinth_id}/forge_updates.json"
displayURL = "https://modrinth.com/mod/argonauts"
logoFile = "icon.png"
authors = "Alex Nijjar, ThatGravyBoat"
credits = ""
description = "Modern Teams mod!"

[[dependencies.argonauts]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.argonauts]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.argonauts]]
modId = "resourcefullib"
mandatory = true
versionRange = "[${resourcefullib_version},)"
ordering = "NONE"
side = "BOTH"