modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/argonauts/issues"

[[mods]]
modId = "argonauts"
version = "${version}"
displayName = "Argonauts"
updateJSONURL="https://api.modrinth.com/updates/bb2EpKpx/forge_updates.json"
displayURL = "https://modrinth.com/mod/argonauts"
logoFile = "icon.png"
authors = "Alex Nijjar, ThatGravyBoat"
credits = ""
description = "A guild and party mod to work and play together with your teammates on a server!"
displayTest="IGNORE_ALL_VERSION"

[[dependencies.argonauts]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.argonauts]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.argonauts]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.1,)"
ordering = "NONE"
side = "BOTH"