modLoader = "javafml"
loaderVersion = "[45,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/${github_name}/issues"

[[mods]]
modId = "argonauts"
version = "${version}"
displayName = "Argonauts"
displayURL = "https://modrinth.com/mod/argonauts"
logoFile = "icon.png"
authors = "Alex Nijjar, ThatGravyBoat"
credits = ""
description = "Modern team mod!"

[[dependencies.argonauts]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.argonauts]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.argonauts]]
modId = "resourcefullib"
mandatory = true
versionRange = "[${resourcefullib_version},)"
ordering = "NONE"
side = "BOTH"