modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/argonauts/issues"

[[mods]]
modId = "argonauts"
version = "${version}"
displayName = "Argonauts"
updateJSONURL="https://api.modrinth.com/updates/bb2EpKpx/forge_updates.json"
displayURL = "https://modrinth.com/mod/argonauts"
logoFile = "icon.png"
authors = "Alex Nijjar, ThatGravyBoat"
credits = ""
description = "A guild and party mod to work and play together with your teammates on a server!"
displayTest="IGNORE_ALL_VERSION"

[[mixins]]
config = "argonauts-common.mixins.json"

[[dependencies.argonauts]]
modId = "neoforge"
type="required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.argonauts]]
modId = "minecraft"
type="required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.argonauts]]
modId = "resourcefullib"
type="required"
versionRange = "[2.4.6,)"
ordering = "NONE"
side = "BOTH"